FROM golang:1.21.6-alpine AS builder
RUN set -eux; apk add --no-cache ca-certificates build-base;
RUN apk add git

WORKDIR /go/src/github.com/stalwart-algoritmiclab/callisto
COPY . ./

RUN make docker-build

FROM alpine:latest
RUN apk update && apk add --no-cache ca-certificates build-base
WORKDIR /callisto
COPY --from=builder /go/src/github.com/stalwart-algoritmiclab/callisto/build/callisto /usr/bin/callisto
CMD [ "callisto" ]
